eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka
    registryFetchIntervalSeconds: 5
  instance:
    hostname: localhost
