eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka
    registryFetchIntervalSeconds: 5
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 3
    prefer-ip-address: true
    instanceId: ${spring.application.name}
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
